### ISSUE TITLE
`TypeError: chalk_1.default is not a function

### ISSUE THREAD

**Issue by jozef-budac** [qase-tms/qase-javascript#146]
I just installed cypress qase reporter v 1.4.1 reporter and when I run cypress with QASE_REPORT=1, I get this error:

`TypeError: chalk_1.default is not a function
    at new CypressQaseReporter (/home/jozef/Lutra/ci2/mergin/web-app/node_modules/cypress-qase-reporter/dist/index.js:56:34)
    at Reporter.setRunnables (/home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/reporter.js:293:21)
    at ProjectBase.<anonymous> (/home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/project-base.js:448:38)
    at Generator.next (<anonymous>:null:null)
    at /home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>:null:null)
    at __awaiter (/home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/node_modules/tslib/tslib.js:113:16)
    at Object.onTestsReceivedAndMaybeRecord (/home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/project-base.js:444:85)
    at SocketE2E.<anonymous> (/home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/socket-base.js:210:32)
    at Generator.next (<anonymous>:null:null)
    at /home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>:null:null)
    at __awaiter (/home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/node_modules/tslib/tslib.js:113:16)
    at Socket.<anonymous> (/home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/packages/server/lib/socket-base.js:209:104)
    at Socket.emit (node:events:394:28)
    at Socket.emitUntyped (/home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/jozef/.cache/Cypress/9.3.1/Cypress/resources/app/packages/socket/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
`

 have this in cypress.json

  "reporter": "cypress-qase-reporter",
    "reporterOptions": {
        "apiToken": "<token>",
        "projectCode": "<project code>",
        "runId": 5,
        "runName": "Test run",
        "runDescription": "Description",
        "logging": true
  }

**Comment by 1ivliev** [comment]
@jozef-budac Greetings. Please tell us about the way to install cypres and about your environment.
Thanks

**Comment by jozef-budac** [comment]
I installed reported using this command:
npm install --save-dev cypress-qase-reporter

This is my package json file:
`{
  "name": "mergin",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint --fix",
    "i18n:report": "vue-cli-service i18n:report --src './src/admin/**/*.?(js|vue)' --locales './src/admin/locales/**/*.json'",
    "cypress:open": "cypress open",
    "cypress:run": "cypress run"
  },
  "dependencies": {
    "@gtm-support/vue2-gtm": "^1.0.0",
    "@mdi/font": "^5.3.45",
    "axios": "^0.21.1",
    "axios-retry": "^3.1.2",
    "core-js": "^3.6.5",
    "country-region-data": "^1.6.0",
    "crypto-js": "^3.1.9-1",
    "date-fns": "^1.29.0",
    "file-saver": "^2.0.5",
    "lodash": "^4.17.15",
    "material-icons": "^0.2.3",
    "mdi-vue": "^1.6.3",
    "node-sass": "^4.9.4",
    "pdfjs-dist": "2.5.207",
    "portal-vue": "^2.1.7",
    "sass-loader": "^8.0.0",
    "stylus-loader": "^3.0.2",
    "tiptap": "^1.19.2",
    "tiptap-extensions": "^1.19.2",
    "vue": "^2.6.11",
    "vue-country-region-select": "^2.0.14",
    "vue-i18n": "^8.15.3",
    "vue-material-design-icons": "^4.7.1",
    "vue-meta": "^2.4.0",
    "vue-pdf": "^4.1.0",
    "vue-router": "^3.5.1",
    "vue-tel-input": "~4.3.0",
    "vue-wysiwyg": "^1.7.2",
    "vuetify": "2.2.11",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.9.0",
    "@vue/cli-plugin-babel": "^4.1.2",
    "@vue/cli-plugin-e2e-cypress": "^4.1.2",
    "@vue/cli-plugin-eslint": "^4.1.2",
    "@vue/cli-plugin-unit-jest": "^4.1.2",
    "@vue/cli-service": "^4.1.2",
    "@vue/eslint-config-standard": "^5.0.1",
    "@vue/test-utils": "1.0.0-beta.30",
    "adm-zip": "^0.5.9",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "cypress": "^9.3.1",
    "cypress-file-upload": "^5.0.8",
    "cypress-image-snapshot": "^4.0.1",
    "cypress-qase-reporter": "^1.4.1",
    "dotenv": "^14.3.0",
    "eslint": "^6.8.0",
    "eslint-config-vuetify": "^0.4.1",
    "eslint-plugin-vue": "^6.1.2",
    "sass": "^1.24.3",
    "smtp-tester": "1.2.0",
    "svg-inline-loader": "^0.8.0",
    "vee-validate": "^3.2.2",
    "vue-chartist": "^2.2.1",
    "vue-cli-plugin-i18n": "^0.6.0",
    "vue-cli-plugin-vuetify": "^2.0.3",
    "vue-template-compiler": "^2.5.17",
    "vue-world-map": "^0.1.1",
    "vuetify-loader": "^1.4.3"
  }
}
`

Do you needs something else?

**Comment by jozef-budac** [comment]
I was able to fix this with manual install of chalk package
```
npm install --save-dev chalk:4.1.2
```
