### ISSUE TITLE
Unable to use playwright-qase-reporter with Typescript

### ISSUE THREAD

**Issue by jamesmeneghello** [qase-tms/qase-javascript#199]
When running tests with QASE_REPORT=1 and with tests written in Typescript, the following occurs:

```
Error: ../../.yarn/cache/playwright-qase-reporter-npm-1.1.3-15346b8cfb-4f76cc6a96.zip/node_modules/playwright-qase-reporter/dist/index.js: JavaScript files must end with .mjs to use import.
    at errorWithFile (/home/.../.yarn/cache/@playwright-test-npm-1.21.1-62716b18c6-b2bf7dc5fd.zip/node_modules/@playwright/test/lib/util.js:218:10)
    at Loader._requireOrImport (/home/.../.yarn/cache/@playwright-test-npm-1.21.1-62716b18c6-b2bf7dc5fd.zip/node_modules/@playwright/test/lib/loader.js:272:145)
    at Loader.loadReporter (/home/.../.yarn/cache/@playwright-test-npm-1.21.1-62716b18c6-b2bf7dc5fd.zip/node_modules/@playwright/test/lib/loader.js:188:27)
    at Runner._createReporter (/home/.../.yarn/cache/@playwright-test-npm-1.21.1-62716b18c6-b2bf7dc5fd.zip/node_modules/@playwright/test/lib/runner.js:142:56)
    at Runner.runAllTests (/home/.../.yarn/cache/@playwright-test-npm-1.21.1-62716b18c6-b2bf7dc5fd.zip/node_modules/@playwright/test/lib/runner.js:177:33)
    at runTests (/home/.../.yarn/cache/@playwright-test-npm-1.21.1-62716b18c6-b2bf7dc5fd.zip/node_modules/@playwright/test/lib/cli.js:194:31)
    at Command.<anonymous> (/home/.../.yarn/cache/@playwright-test-npm-1.21.1-62716b18c6-b2bf7dc5fd.zip/node_modules/@playwright/test/lib/cli.js:83:7)
```

Yarn: 3.0.2 PnP
@playwright/test: 1.21.1
playwright-qase-reporter: *

**Comment by 1ivliev** [comment]
@jamesmeneghello Hi! Please attach examples of files with which there are problems. Working with typescrypt is supported in `playwright-qase-reporter`
Current version `v1.2.0-alpha.2`

**Comment by jamesmeneghello** [comment]
Sure can: https://github.com/jamesmeneghello/qase-ts-example

`yarn` and `yarn test:ci`

**Comment by jamesmeneghello** [comment]
Bump? :)

**Comment by jamesmeneghello** [comment]
FYI, the answer to this:

`jest-qase-reporter` is missing a peerdep to Chalk, so Yarn PNP requires you to add it to `.yarnrc.yml`:

```
jest-qase-reporter@*:
    dependencies:
      chalk: "^4.1.0"
```

The problem we were having is I used `chalk: "*"` which grabbed Chalk v5, which isn't `require()`able. `4.1` works fine.
