### ISSUE TITLE
Encountering error in reportBulk.js when running from AWS Codepipeline

### ISSUE THREAD

**Issue by TJOLIVA** [qase-tms/qase-javascript#209]
getting this error in reportBulk.js
`<html>
<body>

qase: Done
--
134 | qase: Run finished
135 | qase: Project PCG exists
136 | qase: Using run 14 to publish test results
137 | /usr/local/lib/node_modules/newman-reporter-qase/dist/reportBulk.js:6
138 | const config = JSON.parse(process.env?.reporting_config);
139 | ^
140 |  
141 | SyntaxError: Unexpected token '.'
142 | at wrapSafe (internal/modules/cjs/loader.js:915:16)
143 | at Module._compile (internal/modules/cjs/loader.js:963:27)
144 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
145 | at Module.load (internal/modules/cjs/loader.js:863:32)
146 | at Function.Module._load (internal/modules/cjs/loader.js:708:14)
147 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
148 | at internal/main/run_main_module.js:17:47

</body>
</html>`

**Comment by TJOLIVA** [comment]
the issue seems to stem from the default node.js version supported in AWS. 
I simply updated the version of node to 14 and issue was no longer encountered. 
Closing this issue.
