### ISSUE TITLE
issue running cucumberjs-qase-reporter 0.2.9 with @cucumber/cucumber 9.5.1

### ISSUE THREAD

**Issue by odeatomas** [qase-tms/qase-javascript#442]
Hi 
I am running through setting up qase with an existing cucumber js project  
qase version:     "cucumberjs-qase-reporter": "^0.2.9",
cucumberjs version:  "@cucumber/cucumber": "^9.5.1"

i have created a .qaserc config in the root of the project 
when i run the cli command
"cucumber-js -f cucumberjs-qase-reporter --format-options='{"qaseConfig": "./.qaserc"}' features"

I get the following error 
Error: Package subpath './dist/src/messages' is not defined by "exports" in C:\projects\myproject-e2e\node_modules\@cucumber\messages\package.json

any ideas on how to resolve this? 
Thanks

**Comment by BrunoNCD** [comment]
Same issue here, running cucumber-js on the ESM loader, probably related.

**Comment by PatrickBlink** [comment]
Hi I am having the same issue here, any ideas how to resolve, or if @BrunoNCD fix is / will be merged?

"@cucumber/cucumber": "^10.3.1",
"@playwright/test": "^1.41.2",
"cucumberjs-qase-reporter": "^0.2.10",

On node LTS v21.6.1
I also tried with qase-reporter v0.2.9 and v0.2.6 but having the same.

Error: Package subpath './dist/src/messages' is not defined by "exports" in /Users/.../cucumber-playwright/node_modules/@cucumber/messages/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:302:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:649:9)
    at resolveExports (node:internal/modules/cjs/loader:596:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:673:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1135:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/.../cucumber-playwright/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/.../cucumber-playwright/node_modules/cucumberjs-qase-reporter/src/index.ts:13:1) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'


Many Thanks

**Comment by felipocorrea90** [comment]
Same issue here. Is this project still in working condition for CucumberJs?
