### ISSUE TITLE
qase-playwright v2: Test run title not generated by default

### ISSUE THREAD

**Issue by NickVolynkin** [qase-tms/qase-javascript#544]
Test run title should be generated from current timestamp, if it's not specified in the config, CLI or ENV.

```console
$ npx playwright test
...
Running 2 tests using 1 worker
...
  2 passed (4.3s)
qase: Unable to publish the run results to the upstream reporter:
  Caused by:
    Message: Data is invalid.
      title: The title field is required.
      
    Error: Request failed with status code 400
        at createError (./node_modules/axios/lib/core/createError.js:16:15)
        at settle (./node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (./node_modules/axios/lib/adapters/http.js:269:11)
        at IncomingMessage.emit (node:events:531:35)
        at endReadableNT (node:internal/streams/readable:1696:12)
        at processTicksAndRejections (node:internal/process/task_queues:82:21)
  Error: Cannot create run
      at TestOpsReporter.createRun (./node_modules/qase-javascript-commons/dist/reporters/testops-reporter.js:180:19)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at TestOpsReporter.publish (./node_modules/qase-javascript-commons/dist/reporters/testops-reporter.js:47:32)
      at QaseReporter.publish (./node_modules/qase-javascript-commons/dist/qase.js:171:17)
      at PlaywrightQaseReporter.onEnd (./node_modules/playwright-qase-reporter/dist/reporter.js:208:9)
      at ReporterV2Wrapper.onEnd (./node_modules/playwright/lib/reporters/reporterV2.js:91:12)
      at wrapAsync (./node_modules/playwright/lib/reporters/multiplexer.js:79:12)
      at Multiplexer.onEnd (./node_modules/playwright/lib/reporters/multiplexer.js:51:25)
      at InternalReporter.onEnd (./node_modules/playwright/lib/reporters/internalReporter.js:69:12)
      at Runner.runAllTests (./node_modules/playwright/lib/runner/runner.js:84:28)
      at runTests (./node_modules/playwright/lib/program.js:180:93)
      at t.<anonymous> (./node_modules/playwright/lib/program.js:53:7)
```

**Comment by gibiw** [comment]
Fixed
