### ISSUE TITLE
Error message is unclear when API token is absent or invalid

### ISSUE THREAD

**Issue by NickVolynkin** [qase-tms/qase-javascript#562]
Running tests from `examples/cypress` with the default config, having the "example" token, we get the following error message:

```
My First Test
qase: Unable to start test run in the upstream reporter:
Caused by:
    Message: Unauthenticated.
    Error: Request failed with status code 401
        at createError (<homedir>/node_modules/axios/lib/core/createError.js:16:15)
        at settle (<homedir>/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (<homedir>/node_modules/axios/lib/adapters/http.js:269:11)
        at IncomingMessage.emit (node:events:539:35)
        at endReadableNT (node:internal/streams/readable:1345:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
    Error: Cannot create run
        at TestOpsReporter.createRun (<homedir>/qase-javascript-commons/dist/reporters/testops-reporter.js:307:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async TestOpsReporter.checkOrCreateTestRun (<homedir>/qase-javascript-commons/dist/reporters/testops-reporter.js:79:28)
        at async TestOpsReporter.startTestRun (<homedir>/qase-javascript-commons/dist/reporters/testops-reporter.js:53:9)
        at async QaseReporter.startTestRun (<homedir>/qase-javascript-commons/dist/qase.js:128:17)
```

It's unclear what happened and what to do unless you have a deep knowledge of Qase reporters internals. Our customers probably don't have this knowledge.

Instead, a good error message should include:

* What happened on the level of user's scenario (not in the code)
* What they can do to resolve it
* Where to read more

**Comment by gibiw** [comment]
Fixed in the qase-javascript-commons 2.0.11
