### ISSUE TITLE
qase-playwright v2: Unable to upload test results. 400 Bad request in body

### ISSUE THREAD

**Issue by mi4i0** [qase-tms/qase-javascript#648]
Not able to upload test results after test execution

1. Run tests via `QASE_MODE=testops npx playwright test`
2. Wait ending of test run

**Actual result:** [ERROR] qase: Unable to publish the run results to the upstream reporter:
```
[2024-07-31T11:12:18.169Z] [DEBUG] qase: Config: {"configDir":"/Users/mi4i0/GitRepos/autotests","_mode":"test","_isTestServer":false,"_commandHash":"","debug":true,"testops":{"api":{"token":"bfbe39aaa5dcca94e64770f1b8c873eb67979a02eeb6ca57cf92fcc16b54f257"},"project":"AA","uploadAttachments":true,"run":{"complete":true},"plan":{},"batch":{}},"frameworkPackage":"@playwright/test","frameworkName":"playwright","reporterName":"playwright-qase-reporter","report":{"connections":{"local":{}}}}
[2024-07-31T11:30:02.626Z] [DEBUG] qase: Config: {"configDir":"/Users/mi4i0/GitRepos/autotests","_mode":"test","_isTestServer":false,"_commandHash":"","debug":true,"testops":{"api":{"token":"bfbe39aaa5dcca94e64770f1b8c873eb67979a02eeb6ca57cf92fcc16b54f257"},"project":"AA","uploadAttachments":true,"run":{"complete":true},"plan":{},"batch":{}},"frameworkPackage":"@playwright/test","frameworkName":"playwright","reporterName":"playwright-qase-reporter","report":{"connections":{"local":{}}}}
[2024-07-31T11:30:48.894Z] [DEBUG] qase: Config: {"configDir":"/Users/mi4i0/GitRepos/autotests","_mode":"test","_isTestServer":false,"_commandHash":"","debug":true,"testops":{"api":{"token":"bfbe39aaa5dcca94e64770f1b8c873eb67979a02eeb6ca57cf92fcc16b54f257"},"project":"AA","uploadAttachments":true,"run":{"complete":true},"plan":{},"batch":{}},"frameworkPackage":"@playwright/test","frameworkName":"playwright","reporterName":"playwright-qase-reporter","report":{"connections":{"local":{}}}}
[2024-07-31T14:27:42.654Z] [DEBUG] qase: Config: {"configDir":"/Users/mi4i0/GitRepos/autotests","_mode":"test","_isTestServer":false,"_commandHash":"","debug":true,"testops":{"api":{"token":"bfbe39aaa5dcca94e64770f1b8c873eb67979a02eeb6ca57cf92fcc16b54f257"},"project":"AA","uploadAttachments":false,"run":{},"plan":{},"batch":{}},"frameworkPackage":"@playwright/test","frameworkName":"playwright","reporterName":"playwright-qase-reporter","mode":"testops","report":{"connections":{"local":{}}}}
[2024-07-31T14:27:43.840Z] [DEBUG] qase: Starting test run
[2024-07-31T14:27:43.840Z] [DEBUG] qase: Creating test run
[2024-07-31T14:27:44.447Z] [DEBUG] qase: Test run created: 27
[2024-07-31T14:27:44.997Z] [INFO] qase: [32mTest authenticate as Super Admin passed[39m
[2024-07-31T14:27:44.997Z] [DEBUG] qase: Adding test result: {"attachments":[],"author":null,"execution":{"status":"passed","start_time":1722436064.615,"end_time":null,"duration":131,"stacktrace":null,"thread":"0"},"fields":{},"id":"30da5dc2-3052-442a-8bb7-47bf20a95cd4","message":null,"muted":false,"params":{},"relations":{"suite":{"data":[{"title":"setup","public_id":null},{"title":"auth/auth.setup.ts","public_id":null}]}},"run_id":null,"signature":"setup::auth::auth.setup.ts::authenticate_as_super_admin","steps":[{"id":"09a3d309-7d75-4591-a91f-70a15014fe63","step_type":"text","data":{"action":"Before Hooks","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436064.618,"duration":318,"end_time":null},"attachments":[],"steps":[]},{"id":"08cad03f-8e7b-419f-b5bf-12256b7974e5","step_type":"text","data":{"action":"After Hooks","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436064.937,"duration":58,"end_time":null},"attachments":[],"steps":[]}],"testops_id":null,"title":"authenticate as Super Admin"}
[2024-07-31T14:28:17.441Z] [INFO] qase: [32mTest Check of UPLOAD ACHIEVEMENT: required fields | no file and .jpg file | Achievement name and Issuer - empty or 1 symbol | Achievement date - empty or yesterday | CANCEL | SUBMIT passed[39m
[2024-07-31T14:28:17.512Z] [DEBUG] qase: Adding test result: {"attachments":[],"author":null,"execution":{"status":"passed","start_time":1722436065.943,"end_time":null,"duration":14284,"stacktrace":null,"thread":"0"},"fields":{},"id":"5756832c-59ef-4e1f-a4d8-09ce0ac020ca","message":null,"muted":false,"params":{},"relations":{"suite":{"data":[{"title":"Academy","public_id":null},{"title":"academy/achievements/UploadAchievement.spec.ts","public_id":null},{"title":"AA-4366 Check of UPLOAD ACHIEVEMENT","public_id":null}]}},"run_id":null,"signature":"academy::academy::achievements/uploadachievement.spec.ts::aa-4366_check_of_upload_achievement::check_of_upload_achievement:_required_fields_|_no_file_and_.jpg_file_|_achievement_name_and_issuer_-_empty_or_1_symbol_|_achievement_date_-_empty_or_yesterday_|_cancel_|_submit::4366","steps":[{"id":"106ba025-db18-48a1-9f45-e8b0359d95e8","step_type":"text","data":{"action":"Before Hooks","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436065.946,"duration":16268,"end_time":null},"attachments":[],"steps":[{"id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","step_type":"text","data":{"action":"beforeAll hook","expected_result":null},"parent_id":"106ba025-db18-48a1-9f45-e8b0359d95e8","execution":{"status":"passed","start_time":1722436065.946,"duration":15990,"end_time":null},"attachments":[],"steps":[{"id":"a0a8f687-43df-4002-bb3c-f7dd3eb2c531","step_type":"text","data":{"action":"Send POST request to https://api.studytube-staging2.nl/admin-api/academies","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436065.953,"duration":6199,"end_time":null},"attachments":[],"steps":[]},{"id":"ad675c70-222e-4f34-b897-1977768ba336","step_type":"text","data":{"action":"Send PATCH request to https://api.studytube-staging2.nl/admin-api/academies/1624/licences/user","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436072.152,"duration":1039,"end_time":null},"attachments":[],"steps":[]},{"id":"a8cece02-3e5f-4546-abd9-e274eb2efcb9","step_type":"text","data":{"action":"Send PATCH request to https://api.studytube-staging2.nl/admin-api/academies/1624/licences/content","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436073.192,"duration":1127,"end_time":null},"attachments":[],"steps":[]},{"id":"ee4d572a-32c0-4ca1-8aa8-881104ec1676","step_type":"text","data":{"action":"Send PATCH request to https://api.studytube-staging2.nl/admin-api/academies/1624","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436074.319,"duration":754,"end_time":null},"attachments":[],"steps":[]},{"id":"7f4dd85c-23b4-40dd-9c83-ca61ed0ff5ab","step_type":"text","data":{"action":"Send PATCH request to https://api.studytube-staging2.nl/lms/me","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436075.075,"duration":702,"end_time":null},"attachments":[],"steps":[]},{"id":"7bb44ce0-e2e8-4d7c-9e35-8fcb19a62d06","step_type":"text","data":{"action":"Send GET request to academy-users","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436075.777,"duration":470,"end_time":null},"attachments":[],"steps":[]},{"id":"a50c47ea-af23-4f85-b179-336160c5780f","step_type":"text","data":{"action":"Send POST request to user-invites/clear","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436076.248,"duration":371,"end_time":null},"attachments":[],"steps":[]},{"id":"ab0d3450-9ce5-49d3-9267-edda0df095bd","step_type":"text","data":{"action":"Send POST request to user-invites","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436076.619,"duration":411,"end_time":null},"attachments":[],"steps":[]},{"id":"5a2aa4c2-b5a1-4ba6-9a8e-636d13a915e4","step_type":"text","data":{"action":"Send POST request to user-invites/run","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436077.03,"duration":775,"end_time":null},"attachments":[],"steps":[]},{"id":"a25c1b0f-ff96-46a9-a9fb-226eeb04d774","step_type":"text","data":{"action":"Send GET request to permission-groups","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436077.806,"duration":378,"end_time":null},"attachments":[],"steps":[]},{"id":"919c904f-caa1-4739-aaf0-4d4ecfd7f6e3","step_type":"text","data":{"action":"Send PATCH request to permission-groups/9268","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436078.184,"duration":559,"end_time":null},"attachments":[],"steps":[]},{"id":"4317b00a-24da-493c-90de-10d1ba9950a8","step_type":"text","data":{"action":"Send GET request to academy-users","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436078.744,"duration":678,"end_time":null},"attachments":[],"steps":[]},{"id":"6489fc7f-5726-40e5-ac1d-93658bca311a","step_type":"text","data":{"action":"Send PATCH request to permission-groups/9268/assign-managers","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436079.423,"duration":491,"end_time":null},"attachments":[],"steps":[]},{"id":"ab9701c1-1ee0-4737-beb4-f2578e0d76d3","step_type":"text","data":{"action":"Send GET request to academy","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436079.914,"duration":536,"end_time":null},"attachments":[],"steps":[]},{"id":"e6faacfd-3925-476c-b785-a33e9ec888a2","step_type":"text","data":{"action":"Send PATCH request to academy","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436080.45,"duration":918,"end_time":null},"attachments":[],"steps":[]},{"id":"bd4242e6-3ab8-43de-8f8b-332fff53097c","step_type":"text","data":{"action":"Send PATCH request to https://api.studytube-staging2.nl/academy2/user/cookie-consent","expected_result":null},"parent_id":"e00fe60e-2c15-4b33-8687-d5b8c435c953","execution":{"status":"passed","start_time":1722436081.369,"duration":565,"end_time":null},"attachments":[],"steps":[]}]}]},{"id":"715af8a4-88b5-4c2d-98f5-00b41d7fd252","step_type":"text","data":{"action":"Go to Achievements page","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436082.215,"duration":2945,"end_time":null},"attachments":[],"steps":[]},{"id":"2ee077b2-f58a-45c9-a3e5-eb678e0fe5e0","step_type":"text","data":{"action":"Click on upload certificate and check uploadCertificateDialog is opened","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436085.161,"duration":435,"end_time":null},"attachments":[],"steps":[{"id":"f0227be8-2e97-4418-9713-cb0e90727cbe","step_type":"text","data":{"action":"Click button","expected_result":null},"parent_id":"2ee077b2-f58a-45c9-a3e5-eb678e0fe5e0","execution":{"status":"passed","start_time":1722436085.161,"duration":71,"end_time":null},"attachments":[],"steps":[]}]},{"id":"054ff5b8-075a-4a28-99fc-a7d3c48cfc11","step_type":"text","data":{"action":"Check of empty required fields","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436085.596,"duration":4739,"end_time":null},"attachments":[],"steps":[{"id":"3731c0c3-55b4-4618-9a9d-06f56f33aa4d","step_type":"text","data":{"action":"Click button","expected_result":null},"parent_id":"054ff5b8-075a-4a28-99fc-a7d3c48cfc11","execution":{"status":"passed","start_time":1722436085.596,"duration":29,"end_time":null},"attachments":[],"steps":[]},{"id":"33507183-9be7-4ffd-bb77-5015e86f83b6","step_type":"text","data":{"action":"Check alert message","expected_result":null},"parent_id":"054ff5b8-075a-4a28-99fc-a7d3c48cfc11","execution":{"status":"passed","start_time":1722436085.626,"duration":4671,"end_time":null},"attachments":[],"steps":[]},{"id":"5319fc81-3e9c-4d24-b020-b730387f5294","step_type":"text","data":{"action":"Check that input contains error message","expected_result":null},"parent_id":"054ff5b8-075a-4a28-99fc-a7d3c48cfc11","execution":{"status":"passed","start_time":1722436090.297,"duration":14,"end_time":null},"attachments":[],"steps":[]},{"id":"b93fd5b1-e9d2-45db-bdf4-04c15057497b","step_type":"text","data":{"action":"Check that input contains error message","expected_result":null},"parent_id":"054ff5b8-075a-4a28-99fc-a7d3c48cfc11","execution":{"status":"passed","start_time":1722436090.312,"duration":8,"end_time":null},"attachments":[],"steps":[]},{"id":"aba347a8-2d54-453d-b731-39d15682ae54","step_type":"text","data":{"action":"Check that input contains error message","expected_result":null},"parent_id":"054ff5b8-075a-4a28-99fc-a7d3c48cfc11","execution":{"status":"passed","start_time":1722436090.32,"duration":7,"end_time":null},"attachments":[],"steps":[]},{"id":"42d1d128-f7e1-417e-b86a-533e8e1963c6","step_type":"text","data":{"action":"Check that input contains error message","expected_result":null},"parent_id":"054ff5b8-075a-4a28-99fc-a7d3c48cfc11","execution":{"status":"passed","start_time":1722436090.327,"duration":8,"end_time":null},"attachments":[],"steps":[]}]},{"id":"54f31420-1c2f-487e-8242-c41268e7922f","step_type":"text","data":{"action":"Check of CANCEL button","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436090.335,"duration":136,"end_time":null},"attachments":[],"steps":[{"id":"a9c34e91-fd1d-43fa-a2ad-a409001a8f37","step_type":"text","data":{"action":"Click button","expected_result":null},"parent_id":"54f31420-1c2f-487e-8242-c41268e7922f","execution":{"status":"passed","start_time":1722436090.335,"duration":25,"end_time":null},"attachments":[],"steps":[]}]},{"id":"28e5a565-37bd-457d-909d-c97e52124b11","step_type":"text","data":{"action":"Check of entering correct values in required fields","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436090.472,"duration":484,"end_time":null},"attachments":[],"steps":[{"id":"97143d00-1ac4-4a95-8e9e-384709c4e86e","step_type":"text","data":{"action":"Click button","expected_result":null},"parent_id":"28e5a565-37bd-457d-909d-c97e52124b11","execution":{"status":"passed","start_time":1722436090.472,"duration":21,"end_time":null},"attachments":[],"steps":[]},{"id":"e52e4bb2-604d-4d11-962e-760130b73b9b","step_type":"text","data":{"action":"Upload file into input","expected_result":null},"parent_id":"28e5a565-37bd-457d-909d-c97e52124b11","execution":{"status":"passed","start_time":1722436090.863,"duration":24,"end_time":null},"attachments":[],"steps":[]},{"id":"da1c6930-03b3-49fa-9659-2451d056b1a6","step_type":"text","data":{"action":"Fill input with l","expected_result":null},"parent_id":"28e5a565-37bd-457d-909d-c97e52124b11","execution":{"status":"passed","start_time":1722436090.896,"duration":10,"end_time":null},"attachments":[],"steps":[]},{"id":"ecce26d8-8573-4fb2-bd56-bf0392c992b7","step_type":"text","data":{"action":"Fill input with b","expected_result":null},"parent_id":"28e5a565-37bd-457d-909d-c97e52124b11","execution":{"status":"passed","start_time":1722436090.913,"duration":10,"end_time":null},"attachments":[],"steps":[]},{"id":"aa0a127d-02d6-43da-8f6d-40c9a5a10849","step_type":"text","data":{"action":"Fill input with 30 07 2024","expected_result":null},"parent_id":"28e5a565-37bd-457d-909d-c97e52124b11","execution":{"status":"passed","start_time":1722436090.945,"duration":11,"end_time":null},"attachments":[],"steps":[]}]},{"id":"91ec0603-65ee-45eb-b0a9-f5f8da83630e","step_type":"text","data":{"action":"Check of SUBMIT button","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436090.957,"duration":5221,"end_time":null},"attachments":[],"steps":[{"id":"b29336fc-8e55-49a8-b911-a15fdaaf5508","step_type":"text","data":{"action":"Click button","expected_result":null},"parent_id":"91ec0603-65ee-45eb-b0a9-f5f8da83630e","execution":{"status":"passed","start_time":1722436090.957,"duration":21,"end_time":null},"attachments":[],"steps":[]},{"id":"88ea8f31-3dbb-4d26-9c38-b4e886c60c50","step_type":"text","data":{"action":"Check alert message","expected_result":null},"parent_id":"91ec0603-65ee-45eb-b0a9-f5f8da83630e","execution":{"status":"passed","start_time":1722436091.842,"duration":4336,"end_time":null},"attachments":[],"steps":[]}]},{"id":"b2145484-f094-4200-8056-e0b18441bca7","step_type":"text","data":{"action":"After Hooks","expected_result":null},"parent_id":null,"execution":{"status":"passed","start_time":1722436096.178,"duration":1259,"end_time":null},"attachments":[],"steps":[{"id":"fdff55dc-109d-4ec4-86d6-800ae3ab0f14","step_type":"text","data":{"action":"afterAll hook","expected_result":null},"parent_id":"b2145484-f094-4200-8056-e0b18441bca7","execution":{"status":"passed","start_time":1722436096.374,"duration":1063,"end_time":null},"attachments":[],"steps":[{"id":"b3086512-8ce0-43b6-a0b1-2ea7dad010aa","step_type":"text","data":{"action":"Send GET request to https://api.studytube-staging2.nl/admin-api/academies","expected_result":null},"parent_id":"fdff55dc-109d-4ec4-86d6-800ae3ab0f14","execution":{"status":"passed","start_time":1722436096.377,"duration":362,"end_time":null},"attachments":[],"steps":[]},{"id":"b6a379d8-29f1-4ecf-aa82-c0634bd0bbee","step_type":"text","data":{"action":"Send DELETE request to https://api.studytube-staging2.nl/admin-api/academies/1624","expected_result":null},"parent_id":"fdff55dc-109d-4ec4-86d6-800ae3ab0f14","execution":{"status":"passed","start_time":1722436096.739,"duration":697,"end_time":null},"attachments":[],"steps":[]}]}]}],"testops_id":[4366],"title":"Check of UPLOAD ACHIEVEMENT: required fields | no file and .jpg file | Achievement name and Issuer - empty or 1 symbol | Achievement date - empty or yesterday | CANCEL | SUBMIT"}
[2024-07-31T14:28:17.557Z] [DEBUG] qase: Publishing test run results
[2024-07-31T14:28:17.557Z] [DEBUG] qase: Transformed result: {"attachments":[],"comment":null,"defect":false,"param":{},"stacktrace":null,"start_time":1722436064,"status":"passed","steps":[{"status":"passed","attachments":[],"action":"Before Hooks"},{"status":"passed","attachments":[],"action":"After Hooks"}],"time":null,"time_ms":131,"case":{"title":"authenticate as Super Admin","suite_title":"setup\tauth/auth.setup.ts"}}
[2024-07-31T14:28:18.066Z] [ERROR] qase: Unable to publish the run results to the upstream reporter:
 Error: Error on uploading results: Bad request. Body: 
 [{"attachments":[],"comment":null,"defect":false,"param":{},"stacktrace":null,"start_time":1722436064,"status":"passed","steps":[{"status":"passed","attachments":[],"action":"Before Hooks"},{"status":"passed","attachments":[],"action":"After Hooks"}],"time":null,"time_ms":131,"case":{"title":"authenticate as Super Admin","suite_title":"setup\tauth/auth.setup.ts"}},{"attachments":[],"comment":null,"defect":false,"param":{},"stacktrace":null,"start_time":1722436065,"status":"passed","steps":[{"status":"passed","attachments":[],"action":"Before Hooks","steps":[{"status":"passed","attachments":[],"action":"beforeAll hook","steps":[{"status":"passed","attachments":[],"action":"Send POST request to https://api.studytube-staging2.nl/admin-api/academies"},{"status":"passed","attachments":[],"action":"Send PATCH request to https://api.studytube-staging2.nl/admin-api/academies/1624/licences/user"},{"status":"passed","attachments":[],"action":"Send PATCH request to https://api.studytube-staging2.nl/admin-api/academies/1624/licences/content"},{"status":"passed","attachments":[],"action":"Send PATCH request to https://api.studytube-staging2.nl/admin-api/academies/1624"},{"status":"passed","attachments":[],"action":"Send PATCH request to https://api.studytube-staging2.nl/lms/me"},{"status":"passed","attachments":[],"action":"Send GET request to academy-users"},{"status":"passed","attachments":[],"action":"Send POST request to user-invites/clear"},{"status":"passed","attachments":[],"action":"Send POST request to user-invites"},{"status":"passed","attachments":[],"action":"Send POST request to user-invites/run"},{"status":"passed","attachments":[],"action":"Send GET request to permission-groups"},{"status":"passed","attachments":[],"action":"Send PATCH request to permission-groups/9268"},{"status":"passed","attachments":[],"action":"Send GET request to academy-users"},{"status":"passed","attachments":[],"action":"Send PATCH request to permission-groups/9268/assign-managers"},{"status":"passed","attachments":[],"action":"Send GET request to academy"},{"status":"passed","attachments":[],"action":"Send PATCH request to academy"},{"status":"passed","attachments":[],"action":"Send PATCH request to https://api.studytube-staging2.nl/academy2/user/cookie-consent"}]}]},{"status":"passed","attachments":[],"action":"Go to Achievements page"},{"status":"passed","attachments":[],"action":"Click on upload certificate and check uploadCertificateDialog is opened","steps":[{"status":"passed","attachments":[],"action":"Click button"}]},{"status":"passed","attachments":[],"action":"Check of empty required fields","steps":[{"status":"passed","attachments":[],"action":"Click button"},{"status":"passed","attachments":[],"action":"Check alert message"},{"status":"passed","attachments":[],"action":"Check that input contains error message"},{"status":"passed","attachments":[],"action":"Check that input contains error message"},{"status":"passed","attachments":[],"action":"Check that input contains error message"},{"status":"passed","attachments":[],"action":"Check that input contains error message"}]},{"status":"passed","attachments":[],"action":"Check of CANCEL button","steps":[{"status":"passed","attachments":[],"action":"Click button"}]},{"status":"passed","attachments":[],"action":"Check of entering correct values in required fields","steps":[{"status":"passed","attachments":[],"action":"Click button"},{"status":"passed","attachments":[],"action":"Upload file into input"},{"status":"passed","attachments":[],"action":"Fill input with l"},{"status":"passed","attachments":[],"action":"Fill input with b"},{"status":"passed","attachments":[],"action":"Fill input with 30 07 2024"}]},{"status":"passed","attachments":[],"action":"Check of SUBMIT button","steps":[{"status":"passed","attachments":[],"action":"Click button"},{"status":"passed","attachments":[],"action":"Check alert message"}]},{"status":"passed","attachments":[],"action":"After Hooks","steps":[{"status":"passed","attachments":[],"action":"afterAll hook","steps":[{"status":"passed","attachments":[],"action":"Send GET request to https://api.studytube-staging2.nl/admin-api/academies"},{"status":"passed","attachments":[],"action":"Send DELETE request to https://api.studytube-staging2.nl/admin-api/academies/1624"}]}]}],"time":null,"time_ms":14284,"case_id":4366}]
    at TestOpsReporter.processError (/Users/mi4i0/GitRepos/autotests/node_modules/qase-javascript-commons/dist/reporters/testops-reporter.js:468:20)
    at TestOpsReporter.publishResults (/Users/mi4i0/GitRepos/autotests/node_modules/qase-javascript-commons/dist/reporters/testops-reporter.js:149:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TestOpsReporter.publish (/Users/mi4i0/GitRepos/autotests/node_modules/qase-javascript-commons/dist/reporters/testops-reporter.js:163:13)
    at QaseReporter.publish (/Users/mi4i0/GitRepos/autotests/node_modules/qase-javascript-commons/dist/qase.js:217:17)
    at PlaywrightQaseReporter.onEnd (/Users/mi4i0/GitRepos/autotests/node_modules/playwright-qase-reporter/dist/reporter.js:342:9)
    at ReporterV2Wrapper.onEnd (/Users/mi4i0/GitRepos/autotests/node_modules/playwright/lib/reporters/reporterV2.js:91:12)
    at wrapAsync (/Users/mi4i0/GitRepos/autotests/node_modules/playwright/lib/reporters/multiplexer.js:79:12)
    at Multiplexer.onEnd (/Users/mi4i0/GitRepos/autotests/node_modules/playwright/lib/reporters/multiplexer.js:51:25)
    at InternalReporter.onEnd (/Users/mi4i0/GitRepos/autotests/node_modules/playwright/lib/reporters/internalReporter.js:69:12)
    at Runner.runAllTests (/Users/mi4i0/GitRepos/autotests/node_modules/playwright/lib/runner/runner.js:78:28)
    at runTests (/Users/mi4i0/GitRepos/autotests/node_modules/playwright/lib/program.js:207:85)
    at t.<anonymous> (/Users/mi4i0/GitRepos/autotests/node_modules/playwright/lib/program.js:54:7)
``` 

**Expected result:** Data loaded into Qase

P.S. I couldn't share repository for repro, but could book debug session if needed. Just contact me

**Comment by gibiw** [comment]
@mi4i0 Do you have the "Auto create test cases" option enabled in your project settings?
![image](https://github.com/user-attachments/assets/dd66c019-4223-45ae-a235-3177cb9738fd)

**Comment by mi4i0** [comment]
@gibiw thanks. Not expected at all :D. Thanks!
I will make PR for adding this information to the documentation for PW reported.

**Comment by mi4i0** [comment]
@gibiw thanks. Not expected at all :D. Thanks!
I will make PR for adding this information to the documentation for PW reported.
