### ISSUE TITLE
[wdio-qase] Screenshot functionality is not working

### ISSUE THREAD

**Issue by Daniel-benages-at-wiris** [qase-tms/qase-javascript#672]
I have `disableWebdriverScreenshotsReporting: false` on the reporter config and 

`afterTest: async function (
    test,
    context,
    { error, result, duration, passed, retries }
  ) {
    await browser.deleteAllCookies();
    if (error) {
      await browser.takeScreenshot();
    }
  }`

With this configuration the afterRunHook() function is failing because when entering in this if statement 
`if (!disableWebdriverScreenshotsReporting && isScreenshot && commandResult) {
            this.attachFile('Screenshot', Buffer.from(commandResult, 'base64'), 'image/png');
        }`
The buffer method throws this error 
> The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

Indeed after a dirty console.log, the `const commandResult = command.result || undefined;` is of type Object. 

I believe this is a bug, and if not, please show what can I do to make it work.

Thx!

**Comment by gibiw** [comment]
@Daniel-benages-at-wiris try to use `wdio-qase-reporter 1.0.0-beta.4`

**Comment by Daniel-benages-at-wiris** [comment]
Hi @gibiw thanks for the quick update!
It no longer throws an error but the screenshot does not appear in my qase.io project

**Comment by gibiw** [comment]
@Daniel-benages-at-wiris It is very strange, because it works for me. I use such settings in the config:
```typescript
    reporters: [[WDIOQaseReporter, {
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
    }]],
```

Can you share debug logs?

**Comment by Daniel-benages-at-wiris** [comment]
@gibiw I've check and I'm using the exact same settings in the config. 

I think these are the relevant logs
```
[0-0] [DEBUG] qase: Adding test result: {"id":"177464fa-3e85-40fa-bf7d-21672bc3fc9c","title":"should visit  for Microsoft 365 AppSource Page","signature":"","run_id":null,"testops_id":[123],"execution":{"status":"failed","start_time":1725959774.086,"end_time":null,"duration":6,"stacktrace":"    Error: No window found with title, url or name matching \"ERROR\"\n        at async DownloadPage.assertWindowTitle (file:///C:/Users/Daniel/Documents/gitRepos/-store-e2e-tests/test/pageobjects/downloadPages/download.page.ts:25:9)\n        at async DownloadPage.landsOnPage (file:///C:/Users/Daniel/Documents/gitRepos/-store-e2e-tests/test/pageobjects/downloadPages/download.page.ts:21:9)\n        at async Context.<anonymous> (file:///C:/Users/Daniel/Documents/gitRepos/-store-e2e-tests/test/specs/downloadFiles/download.e2e.ts:14:9)\n--- End of stack trace ---\n","thread":"0-0"},"fields":{},"attachments":[{"file_path":null,"size":172320,"id":"62337161-c105-4926-bf16-875d370f6fed","file_name":"Screenshot.png","mime_type":"image/png","content":{"type":"Buffer","data":[**------SUPER LONG LIST OF INTEGERS SEPARATED BY COMMAS------**]}}],"steps":[],"params":{},"group_params":{},"author":null,"relations":{"suite":{"data":[{"title":" Store main download page","public_id":null}]}},"muted":false,"message":"CompoundError: One or more errors occurred. ---\nNo window found with title, url or name matching \"\n--- End o

[0-0] [DEBUG] qase: Transformed result: {"attachments":[],"comment":"CompoundError: One or more errors occurred. ---\nNo window found with title, url or name matching \"ERROR\"\n--- End of error message ---\n","defect":false,"param":{},"param_groups":[],"stacktrace":"    Error: No window found with title, url or name matching \"ERROR\"\n        at async DownloadPage.assertWindowTitle (file:///C:/Users/Daniel/Documents/gitRepos/-store-e2e-tests/test/pageobjects/downloadPages/download.page.ts:25:9)\n        at async DownloadPage.landsOnPage (file:///C:/Users/Daniel/Documents/gitRepos/-store-e2e-tests/test/pageobjects/downloadPages/download.page.ts:21:9)\n        at async Context.<anonymous> (file:///C:/Users/Daniel/Documents/gitRepos/-store-e2e-tests/test/specs/downloadFiles/download.e2e.ts:14:9)\n--- End of stack trace ---\n","start_time":1725959774,"status":"failed","steps":[],"time":null,"time_ms":6,"case_id":123,"case":{"title":"should visit  for Microsoft 365 AppSource Page","suite_title":" Store main download page","description":null,"postconditions":null,"preconditions":null}}
```
I've substituted the encoded png, but it looked like [111,93,142,12,120,203,83,217] just a lot longer. That transformed result without the attachment looks suspicious.

Let me know if you need anything else!

**Comment by gibiw** [comment]
@Daniel-benages-at-wiris  Have you enabled attachment uploading in the reporter config (qase.config.json)?
<img width="475" alt="image" src="https://github.com/user-attachments/assets/07ac3ad2-cd7f-40e5-9899-f24af37c8674">

**Comment by Daniel-benages-at-wiris** [comment]
@gibiw That did it! I'm closing the ticket then. 

Thanks! 😀
